# ZJCTF 2019 wanengmima

version: "2"

services:

  web:
    build: .
    image: kanowill/zjctf_2019_wannengmima
    restart: always
    ports:
      - "127.0.0.1:8302:80"
    environment:
      - FLAG=flag{glzjin_wants_a_girl_firend}
